CC=gcc
CFLAGS=-Wall -O2 -g -ansi -static -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE
AR=ar.exe
RANLIB=ranlib.exe

LIB=libsha2.lib
LIBSRC=sha2.c
LIBOBJ=$(LIBSRC:.c=.o)

all:	libsha2.lib

libsha2.lib: $(LIBOBJ)
	$(AR) rc libsha2.lib $(LIBOBJ)
	$(RANLIB) libsha2.lib

.c.o:
	$(CC) $(CFLAGS) -static -c $< -o $@

clean:
	del $(LIBOBJ)

distclean:	clean
	del libsha2.lib
