######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 28 21:04:48 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qt debug
QT += xml

DESTDIR = ./bin
MOC_DIR = ./moc
OBJECTS_DIR = ./obj

# Input
HEADERS += vue_test.h xmlgridparser.h
SOURCES += vue_test.cpp xmlgridparser.cpp
