#! /bin/bash

cd BDMV
toupper.py
cd ..

mv ./BDMV/INDEX.BDMV ./BDMV/INDEX.BDM
mv ./BDMV/MOVIEOBJECT.BDMV ./BDMV/MOVIEOBJ.BDM
mv ./BDMV/BACKUP/INDEX.BDMV ./BDMV/BACKUP/INDEX.BDM
mv ./BDMV/BACKUP/MOVIEOBJECT.BDMV ./BDMV/BACKUP/MOVIEOBJ.BDM
